version: "3"
services:
  teampass-web:
    image: teampass:3.1.2
    networks:
      - teampassnt
    restart: unless-stopped
    volumes:
      - ./settings.php:/var/www/html/includes/config/settings.php
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: yobasystems/alpine-mariadb:latest
    networks:
      - teampassnt
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_SUPERSECRET_PASSWORD
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: YOUR_SECRET_PASSWORD
      MYSQL_USER: teampass
    volumes:
      - ./teampass-db:/var/lib/mysql

networks:
  teampassnt:
    driver: bridge
